apiVersion: v2
type: application
name: events-exporter
version: 0.0.4
kubeVersion: ">=1.10.0-0"
description: "Prometheus exporter that collects Kubernetes cluster events and exposes them as metric samples."
